# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "00a4f77afa6d214fb186b7bd67c4852f"
name = "UNLIMITED-BIKING-APP"
handle = "unlimited-biking-app"
application_url = "https://programming-russia-sv-computational.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "kaminicc.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_inventory,read_orders,read_products,write_inventory,write_product_listings,write_products"

[auth]
redirect_urls = [
  "https://programming-russia-sv-computational.trycloudflare.com/auth/callback",
  "https://programming-russia-sv-computational.trycloudflare.com/auth/shopify/callback",
  "https://programming-russia-sv-computational.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"

  [[webhooks.subscriptions]]
  topics = [ "products/create" ]
  uri = "/webhooks/products/create"

  [[webhooks.subscriptions]]
  topics = [ "products/update" ]
  uri = "/webhooks/products/update"

[pos]
embedded = false
